// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVowz5kysg67nPH-oH_uOCKuq2iyu7Qg',
    appId: '1:1047792775928:web:29d7fc8b690b857cccc10d',
    messagingSenderId: '1047792775928',
    projectId: 'gripometernotif',
    authDomain: 'gripometernotif.firebaseapp.com',
    storageBucket: 'gripometernotif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLM7_SU1sEZ_juPGoC4gk67JoRgQi3ClU',
    appId: '1:1047792775928:android:75d4fd306472d456ccc10d',
    messagingSenderId: '1047792775928',
    projectId: 'gripometernotif',
    storageBucket: 'gripometernotif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsPXnpeJYbvRgb8D1N0YhHay6BW55n7jU',
    appId: '1:1047792775928:ios:b0c8225b0a58094fccc10d',
    messagingSenderId: '1047792775928',
    projectId: 'gripometernotif',
    storageBucket: 'gripometernotif.firebasestorage.app',
    iosBundleId: 'com.example.waterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsPXnpeJYbvRgb8D1N0YhHay6BW55n7jU',
    appId: '1:1047792775928:ios:b0c8225b0a58094fccc10d',
    messagingSenderId: '1047792775928',
    projectId: 'gripometernotif',
    storageBucket: 'gripometernotif.firebasestorage.app',
    iosBundleId: 'com.example.waterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVowz5kysg67nPH-oH_uOCKuq2iyu7Qg',
    appId: '1:1047792775928:web:e6db3904f00c0f97ccc10d',
    messagingSenderId: '1047792775928',
    projectId: 'gripometernotif',
    authDomain: 'gripometernotif.firebaseapp.com',
    storageBucket: 'gripometernotif.firebasestorage.app',
  );
}
